name: Build Linux

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache CUDA Toolkit
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/cuda
          /var/cuda-repo-ubuntu2204-12-2-local
        key: cuda-${{ runner.os }}-${{ hashFiles('**/*.deb') }}
        restore-keys: |
          cuda-${{ runner.os }}-

    - name: Install CUDA 12.2
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        wget https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/cuda-repo-ubuntu2204-12-2-local_12.2.2-535.104.05-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu2204-12-2-local_12.2.2-535.104.05-1_amd64.deb
        sudo cp /var/cuda-repo-ubuntu2204-12-2-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cuda
      shell: bash

    - name: Install C++20
      run: |
        sudo apt-get install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11
        sudo update-alternatives --config gcc
      shell: bash
    
    - name: Install OpenMPI
      run: |
        sudo apt-get install -y openmpi-bin
        sudo apt-get install -y libopenmpi-dev
      shell: bash
    
    - name: Install HDF5
      run: |
        sudo apt-get install -y libatlas-base-dev
      shell: bash

    - name: Install NetCDF
      run: |
        sudo apt-get install -y libnetcdf-dev
        sudo apt-get install -y libnetcdf-c++4-dev
      shell: bash

    - name: Install json cpp
      run: |
        sudo apt-get install -y libjsoncpp-dev
      shell: bash
    
    - name: Install zlib
      run: |
        sudo apt-get install zlib1g-dev
      shell: bash
    
    - name: Install libcurl
      run: |
        sudo apt-get install libhdf5-dev
      shell: bash
    
    - name: Install cblas
      run: |
        sudo apt-get install libblas-dev
      shell: bash